### ISSUE TITLE
Where is the NJPS translation of Tanakh?

### ISSUE THREAD

**Issue by joepin** [Sefaria/Sefaria-Export#7]
I was looking for this specific translation, which I know exists on Sefaria's website, but couldn't find it in this repo (see [here, for example](https://www.sefaria.org/Genesis.1?ven=Tanakh:_The_Holy_Scriptures,_published_by_JPS&lang=bi&aliyot=1) of this translation being used).

Thanks for all your hard work! Our program, [Tanach Study](https://tanachstudy.com) has benefited tremendously from your texts.

**Comment by edamboritz** [comment]
Hi, 
We are very glad your project is benefiting from Sefaria!
The JPS 1985 translation is not present in our export because it is under copyright to JPS and is therefore only available through Sefaria itself and not for re-use. 
We do have several other English language translations that are publicly available. 
You can always refer to specific copyright status in the table of contents of each book, under "versions". 
e.g. https://www.sefaria.org.il/Genesis?lang=he

**Comment by joepin** [comment]
Ah yeah, I figured it would be something like that. Thanks again for everything!
